### ISSUE TITLE
Add a "apostrophe-dialog-box:opened" event

### ISSUE THREAD

**Issue by Tokimon** [apostrophecms/apostrophe-dialog-box#26]
## The problem to solve

I currently have to stop a video that is placed inside a Dialog and I wanted to hook up to the close event to stop it, just to realize that there aren't any. This is a strange exclusion, that would be nice and actually pretty natural to have.

## Proposed solution

If you could add something like this

```js
apos.utils.emit(document.body, 'apostrophe-dialog-box:closed', {
  dialogId: this.id
});
```
to the [`closeDialog` function](https://github.com/apostrophecms/apostrophe-dialog-box/blob/852f1fa191254c5e902fbed9d80341b3428093bb/public/js/always.js#L21) so that we can bind handlers to this event, it would be really useful.

## Alternatives

There is not much of an alternative unless I have to re-add this functionality myself.

## Additional context

N/A

**Comment by abea** [comment]
@Tokimon That's a good idea. We'd be happy to review a PR if you'd like to contribute that. It seems you already have an idea of how to implement the change.

**Comment by Tokimon** [comment]
Alright I will get on it then

**Comment by Tokimon** [comment]
PR Created
